name: Pre-commit

on:
  push:
    branches:

jobs:
  pre-commit:
    name: Check hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: pipenv

      - name: Install Python dependencies
        run: |
          pipx install pipenv
          pipenv install --dev

      - name: Run hooks
        run: pipenv run pre-commit run -a
