name: Pre-commit

on:
  push:
    branches:

jobs:
  pre-commit:
    name: Check hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set clang-format version
        run: |
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-12 100
          sudo update-alternatives --set clang-format /usr/bin/clang-format-12

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          cache: pipenv

      - name: Install Python dependencies
        run: |
          pipx install pipenv
          pipenv install --dev

      - name: Run hooks
        run: pipenv run pre-commit run -a
