name: Pre-commit

on:
  push:
    branches:

jobs:
  pre-commit:
    name: Check hooks
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install Python dependencies
        run: poetry install

      - name: Run hooks
        run: poetry run pre-commit run -a
