name: Bump version

on:
  push:
    branches: [main]

jobs:
  bump-version:
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    name: Bump version and create changelog with commitizen
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ github.token }}
          branch: main
      - name: Print Version
        run: echo Bumped to version ${{ steps.cz.outputs.version }}
