name: Bump version

on:
  push:
    branches: [main]

jobs:
  bump-version:
    name: Bump version and create changelog with commitizen
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ github.token }}
          branch: main
